language: r
latex: true
sudo: false
warnings_are_errors: TRUE
r:
  - devel
  - release

env:
  - _R_CHECK_FORCE_SUGGESTS_=true
    _R_CHECK_CRAN_INCOMING_=true

r_binary_packages:
  - lme4

cache: 
  - packages
